package pipeline

import (
	"context"
	"errors"

	"github.com/ikwukao/strata-log/internal/ingest"
)

// LogProcessor adapts the generic Pipeline to Strata-Log log ingestion.
type LogProcessor struct {
	pipeline *Pipeline[ingest.LogEntry]
}

// NewLogProcessor creates a processor for structured log entries.
func NewLogProcessor(
	ctx context.Context,
	workers int,
	bufferSize int,
	handler Handler[ingest.LogEntry],
) (*LogProcessor, error) {
	p, err := New(ctx, workers, bufferSize, handler)
	if err != nil {
		return nil, err
	}

	return &LogProcessor{
		pipeline: p,
	}, nil
}

// Submit sends a log entry to the processing pipeline.
func (p *LogProcessor) Submit(entry ingest.LogEntry) error {
	err := p.pipeline.Submit(entry)

	switch {
	case err == nil:
		return nil

	case errors.Is(err, ErrClosed):
		return ingest.ErrProcessorClosed

	default:
		return ingest.ErrProcessorFull
	}
}

// Errors returns processing errors generated by workers.
func (p *LogProcessor) Errors() <-chan error {
	return p.pipeline.Errors()
}

// Close gracefully drains accepted log entries before shutting down.
func (p *LogProcessor) Close() {
	p.pipeline.Close()
}
